### ISSUE TITLE
Artifacts in DMA2D

### ISSUE THREAD

**Issue by papadkostas** [lvgl/lv_port_stm32f769_disco#1]
It is known that when the DMA2D is working we get artifacts on the screen.
So i open this up if anyone's arround trying to find the issue together.
I tried to disable DI cache and the artifacts are gone, but I get average 380ms for each frame.
Also tried to used latest CMSIS and HAL drivers but the issue remains.

**Comment by embeddedt** [comment]
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.
