### ISSUE TITLE
Changing the color depth from 16 to 32 bit.

### ISSUE THREAD

**Issue by devjeet-adben** [lvgl/lv_port_stm32f769_disco#13]
I wanted to try 32 bit color depth but cloning the project and just changing 

From
#define LV_COLOR_DEPTH 16 

To
#define LV_COLOR_DEPTH 32

below is the attached image, 
![imgagee](https://github.com/user-attachments/assets/f5358615-7727-4b16-8872-3b68066180a9)

Is there any other configuration which needed to changed?

**Comment by kisvegabor** [comment]
I don't have this board with me now, but these are suspicious to me: [here](https://github.com/lvgl/lv_port_stm32f769_disco/blob/master/hal_stm_lvgl/tft/tft.c#L536) and [here](https://github.com/lvgl/lv_port_stm32f769_disco/blob/master/hal_stm_lvgl/tft/tft.c#L437) the `* 2` means hard coding to 2 bytes.

**Comment by devjeet-adben** [comment]
> I don't have this board with me now, but these are suspicious to me: [here](https://github.com/lvgl/lv_port_stm32f769_disco/blob/master/hal_stm_lvgl/tft/tft.c#L536) and [here](https://github.com/lvgl/lv_port_stm32f769_disco/blob/master/hal_stm_lvgl/tft/tft.c#L437) the `* 2` means hard coding to 2 bytes.

Yeah this works. 
Thank you
