### ISSUE TITLE
Adapting to the newest STM32CubeIDE project structure

### ISSUE THREAD

**Issue by icodk** [lvgl/lv_port_stm32f769_disco#4]
@kisvegabor 
Firstly, I would like to  inform you you that this repository works flawlessly  on my STM32F769I-DISCO board
when build with the newest(1.4.2)  CubeIDE.
This is a bit long but it is in now way a complaint  or dissatisfaction with the lvgl project. On the contrary, I would like to use 
lvgl in an STM32F769NIH6 project, where my starting point is an STM32F769I-DISCO board. I think it (lvgl) is a better fit to my project then TouchGFX or Embedded Wizard.
However, the project structure  of this rep. is incompatible with a new CubeIDE project generated based on a hardware description file *.ioc, which  is how the CubeIDE define mcu configuration. Specifically, I would like to avoid SDRAM if possible and to add other hardware facilities, for example Ethernet, which is very easy to configure through ioc file.
Also in this rep. there is a Utilities folder with font folder that duplicate to some extent the font folder: vgl\src\lv_font
To prevent duplicate functions linker errors. the font folder in the Utilities folder was filtered  out in the project properties.
Other files in the Utilities folde are not being used at all in the project (sound etc) but exist in the rep.
Is it possible to add a rep. for  STM32F769I-DISCO   that was generated  by the CubeIDE, where all the hardware definitions are gathered in the project's ioc file and and where all lvgl related configuration is clearly placed in lv_conf.h and where the option to use SDRAM or not is available ?

Thanks

**Comment by kisvegabor** [comment]
Hi,

> Is it possible to add a rep. for STM32F769I-DISCO that was generated by the CubeIDE, where all the hardware definitions are gathered in the project's ioc file and and where all lvgl related configuration is clearly placed in lv_conf.h and where the option to use SDRAM or not is available ?

Definitely yes! It was asked by others too, so it seems people are interested in it (not a big surprise as  CubeMX is very popular).

What is the current state of your experiments? Could you finally clean up the repo to work with ioc? If you can you send a Pull request?
